Caitlin ep05
ocean-tracking-network/2021-04-13-act-workshop pull request #35
Opened 2021-05-19 14:48 UTC by CaitlinBate

all code for Telemetry Reports - Array Operators, for each node.

2021-05-26 17:01 UTC, jackVanish reviewed
Might be good to mention we can save to other formats with the ggsave function; I don't like to leave anything implicit. Other than that, though, nothing leaps out at me.

2021-05-26 17:12 UTC, jdpye requested changes
Only very minor changes needed, great amount of flavour text in there now and this lesson stands alone very nicely.

2021-05-26 17:12 UTC, jdpye commented on _episodes/05-r-telemetry-report-array.md
> +An interactive map can contain more information than a static map. Here we will explore the package `plotly` to create interactive "slippery" maps. These allow you to explore your map in different wa
it's 'slippy' https://wiki.openstreetmap.org/wiki/Slippy_Map

2021-05-26 18:51 UTC, CaitlinBate commented
changes made and pushed

2021-06-09 18:09 UTC, jackVanish reviewed
Other than a couple of things noted here, I think this looks solid.

2021-06-09 18:09 UTC, jackVanish commented on _episodes/05-r-telemetry-report-array.md
> +# How many of each animals did we detect from each collaborator, by species, per station
Should be "How many of each animal"

2021-06-09 18:09 UTC, jackVanish commented on _episodes/05-r-telemetry-report-array.md
> +First, we will set our basemap's aesthetics and bounding box and assign this information (as a list) to a geo_styling variable. Then, we choose which Deployment Metadata dataset we wish to use and id
My preference would be to break this up and interleave each step with the appropriate code, but that's just a style thing, I leave it up to you to pull the trigger on that if you agree that it's appropriate.

2021-06-11 14:49 UTC, CaitlinBate commented
made all the changes requested. going to merge

2021-06-11 14:49 UTC, merged